[package]
name = "cookbookc"
version = "0.1.0"
authors = ["0xf00 <foo@anima.tech>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
handlebars = "3.2.1"
regex = "1.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0.57"
